language: python
python:
  - "3.3"
  - "pypy"
  - "2.7"
  - "2.6"

# Twisted doesn't have a requirements file so install in place to get
# the dependencies.
install: pip install --editable .
# Run local trial
script: python setup.py test --test-suite=twisted.names.test
