language: python
python:
  - "3.3"
#  - "pypy" # too slow
  - "2.7"
  - "2.6"


env:
  - "TEST_TYPE=pyflakes"
  - "TEST_TYPE=trial"


matrix:
  exclude:
    - python: ""
      env: ""

  include:
    - python: "2.7"
      env: "TEST_TYPE=pyflakes"
    - python: "2.7"
      env: "TEST_TYPE=trial"
    - python: "2.6"
      env: "TEST_TYPE=trial"
    - python: "3.3"
      env: "TEST_TYPE=trial"


install:
  - "pip install pydoctor"
  - "pip install pyflakes"
  - "pip install --editable ."


script: "python setup.py travistest"
