language: python
python:
  - "3.3"
#  - "pypy"
  - "2.7"
#  - "2.6"


env:
  - TEST_TYPE=pyflakes
  - TEST_TYPE=twistedchecker
  - TEST_TYPE=trial

install:
  - pip install pyflakes
#  - pip install twistedchecker
  - pip install coverage
  - pip install --editable .

script: python setup.py travistest
